![Ironhack logo](https://i.imgur.com/1QgrNNw.png)

# Lab | Numpy

## Introduction

An important ability of a data scientist/data engineer is to know where and how to find information that helps you to accomplish your work. In the exercise, you will both practice the Numpy features we discussed in the lesson and learn new features by looking up documentations and references. You will work on your own but remember the teaching staff is at your service whenever you encounter problems.

## Getting Started
There are a bunch of comments which instruct what you are supposed to do step by step. Follow the order of the instructions from top to bottom. Read each instruction carefully and provide your answer beneath it. You should also test your answers to make sure your responses are correct. If one of your responses is incorrect, you may not be able to proceed because later responses may depend upon previous responses.


## Resources

Some of the questions in the assignment are not covered in our lesson. You will learn how to efficiently look up the information on your own. Below are some resources you can find the information you need.

[Numpy User Guide](https://docs.scipy.org/doc/numpy/user/index.html)

[Numpy Reference](https://docs.scipy.org/doc/numpy/reference/)

[Google Search](https://www.google.com/search?q=how+to+use+numpy)



# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
!pip install numpy
import numpy as np

You should consider upgrading via the 'c:\users\letic\appdata\local\programs\python\python38-32\python.exe -m pip install --upgrade pip' command.


#### 2. Print your NumPy version.

In [11]:
# your code here
np.__version__

'1.19.1'

#### 3. Generate a 3x2x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

**Example of output**:
````python
[[[0.29932768, 0.85812686, 0.75266145, 0.09278988, 0.78358352],
  [0.13437453, 0.65695946, 0.82047594, 0.09764179, 0.52230096]],
 
 [[0.54248247, 0.06431281, 0.65902257, 0.92736679, 0.3302839 ],
  [0.86867236, 0.33960592, 0.62295821, 0.74563567, 0.24351584]],
 
 [[0.21276812, 0.06917533, 0.35106591, 0.82273425, 0.7910178 ],
  [0.37768961, 0.56107736, 0.99965953, 0.97615549, 0.2445537 ]]]
````

In [12]:
# Method 1
a=np.random.randint(0,10,size=(3,2,5))
a

array([[[5, 9, 2, 3, 2],
        [5, 3, 0, 6, 3]],

       [[0, 2, 8, 2, 0],
        [6, 9, 5, 0, 6]],

       [[0, 3, 9, 8, 1],
        [1, 0, 1, 9, 3]]])

In [13]:
# Method 2
np.random.choice([0, 1], size=(3,2,5), p=[0.5, 0.5])

array([[[1, 0, 0, 1, 1],
        [1, 1, 0, 0, 1]],

       [[1, 1, 0, 1, 0],
        [0, 0, 0, 0, 0]],

       [[0, 1, 1, 0, 1],
        [0, 1, 0, 0, 1]]])

In [14]:
# Method 3
a=np.random.random((3,2,5))
a

array([[[0.74613522, 0.42307971, 0.27336438, 0.06446082, 0.83692143],
        [0.76583375, 0.92720415, 0.19807632, 0.98395152, 0.41910702]],

       [[0.11506398, 0.27676418, 0.91471331, 0.62527598, 0.89453859],
        [0.90795555, 0.16802186, 0.76177159, 0.60773445, 0.40486619]],

       [[0.41023143, 0.06989725, 0.02931532, 0.23889179, 0.59646613],
        [0.02337149, 0.38677514, 0.35447234, 0.48550978, 0.39831896]]])

#### 4. Print *a*.


In [15]:
# your code here
print(a)

[[[0.74613522 0.42307971 0.27336438 0.06446082 0.83692143]
  [0.76583375 0.92720415 0.19807632 0.98395152 0.41910702]]

 [[0.11506398 0.27676418 0.91471331 0.62527598 0.89453859]
  [0.90795555 0.16802186 0.76177159 0.60773445 0.40486619]]

 [[0.41023143 0.06989725 0.02931532 0.23889179 0.59646613]
  [0.02337149 0.38677514 0.35447234 0.48550978 0.39831896]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

Expected output:

````python
      [[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]]
````

In [16]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [17]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [18]:
# your code here
print(a.shape)
print(b.shape)
if a.shape==b.shape:
    print('Yes, they have the same size.')
else:
    print("No, they don't.")

(3, 2, 5)
(5, 2, 3)
No, they don't.


#### 8. Are you able to add *a* and *b*? Why or why not?


In [19]:
# your answer here
a+b #I can't do it because the arrays have different sizes

ValueError: operands could not be broadcast together with shapes (3,2,5) (5,2,3) 

#### 9. Reshape *b* so that it has the same structure of *a* (i.e. become a 3x2x5 array). Assign the reshaped array to variable *c*.

Expected output:

````python
      [[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]]
````

In [20]:
# your code here
c=b.reshape(3,2,5)
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [21]:
# your code/answer here
d=a+c
d
#Because the both arrays, a and c have the same size (3,2,5)

array([[[1.74613522, 1.42307971, 1.27336438, 1.06446082, 1.83692143],
        [1.76583375, 1.92720415, 1.19807632, 1.98395152, 1.41910702]],

       [[1.11506398, 1.27676418, 1.91471331, 1.62527598, 1.89453859],
        [1.90795555, 1.16802186, 1.76177159, 1.60773445, 1.40486619]],

       [[1.41023143, 1.06989725, 1.02931532, 1.23889179, 1.59646613],
        [1.02337149, 1.38677514, 1.35447234, 1.48550978, 1.39831896]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [22]:
# your code/answer here
print('a=',a)
print('d=',d)
d-a
'The difference is one'

a= [[[0.74613522 0.42307971 0.27336438 0.06446082 0.83692143]
  [0.76583375 0.92720415 0.19807632 0.98395152 0.41910702]]

 [[0.11506398 0.27676418 0.91471331 0.62527598 0.89453859]
  [0.90795555 0.16802186 0.76177159 0.60773445 0.40486619]]

 [[0.41023143 0.06989725 0.02931532 0.23889179 0.59646613]
  [0.02337149 0.38677514 0.35447234 0.48550978 0.39831896]]]
d= [[[1.74613522 1.42307971 1.27336438 1.06446082 1.83692143]
  [1.76583375 1.92720415 1.19807632 1.98395152 1.41910702]]

 [[1.11506398 1.27676418 1.91471331 1.62527598 1.89453859]
  [1.90795555 1.16802186 1.76177159 1.60773445 1.40486619]]

 [[1.41023143 1.06989725 1.02931532 1.23889179 1.59646613]
  [1.02337149 1.38677514 1.35447234 1.48550978 1.39831896]]]


'The difference is one'

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [23]:
# your code here
a*c
e=a*c
print(e)

[[[0.74613522 0.42307971 0.27336438 0.06446082 0.83692143]
  [0.76583375 0.92720415 0.19807632 0.98395152 0.41910702]]

 [[0.11506398 0.27676418 0.91471331 0.62527598 0.89453859]
  [0.90795555 0.16802186 0.76177159 0.60773445 0.40486619]]

 [[0.41023143 0.06989725 0.02931532 0.23889179 0.59646613]
  [0.02337149 0.38677514 0.35447234 0.48550978 0.39831896]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [24]:
# your code/answer here
print(e)
print(a)
#They're equal because e recieve the value of a*c, where c is a array of ones. And one is the neutral element of multiplication,

[[[0.74613522 0.42307971 0.27336438 0.06446082 0.83692143]
  [0.76583375 0.92720415 0.19807632 0.98395152 0.41910702]]

 [[0.11506398 0.27676418 0.91471331 0.62527598 0.89453859]
  [0.90795555 0.16802186 0.76177159 0.60773445 0.40486619]]

 [[0.41023143 0.06989725 0.02931532 0.23889179 0.59646613]
  [0.02337149 0.38677514 0.35447234 0.48550978 0.39831896]]]
[[[0.74613522 0.42307971 0.27336438 0.06446082 0.83692143]
  [0.76583375 0.92720415 0.19807632 0.98395152 0.41910702]]

 [[0.11506398 0.27676418 0.91471331 0.62527598 0.89453859]
  [0.90795555 0.16802186 0.76177159 0.60773445 0.40486619]]

 [[0.41023143 0.06989725 0.02931532 0.23889179 0.59646613]
  [0.02337149 0.38677514 0.35447234 0.48550978 0.39831896]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [25]:
# your code here
d_max=d.max()
d_min=d.min()
d_mean=d.mean()
print(d_max)
print(d_min)
print(d_mean)

1.9839515195775292
1.023371487441306
1.4769363202869608


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 3x2x5) as *d* using `np.empty`.


In [26]:
# your code here
f=np.empty([3,2,5])
print(f)

[[[0.74613522 0.42307971 0.27336438 0.06446082 0.83692143]
  [0.76583375 0.92720415 0.19807632 0.98395152 0.41910702]]

 [[0.11506398 0.27676418 0.91471331 0.62527598 0.89453859]
  [0.90795555 0.16802186 0.76177159 0.60773445 0.40486619]]

 [[0.41023143 0.06989725 0.02931532 0.23889179 0.59646613]
  [0.02337149 0.38677514 0.35447234 0.48550978 0.39831896]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [27]:
# your code here
list(d)
list(f)
for i in range(len(d)):
    for x in range(len(d[i])):
        for z in range(len(d[i][x])): 
            if((d[i][x][z]> d_min) & (d[i][x][z]< d_mean)):
                f[i][x][z]=25
            if((d[i][x][z]> d_mean) & (d[i][x][z]< d_max)):
                f[i][x][z]=75
            if(d[i][x][z]==d_mean):
                f[i][x][z]=50
            if(d[i][x][z]==d_min):
                f[i][x][z]=0
            if(d[i][x][z]==d_max):
                f[i][x][z]=100
f=np.array(f)

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
  [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981]],

[[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042],
  [1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381]],

[[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
 [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.  75.  75.  25.  75.]
  [ 75.  75.  25.  25.  25.]]

 [[ 75.  25.  75.  75.  75.]
  [ 25.  25.  25.  25. 100.]]

 [[ 75.  75.  75.  75.  75.]
  [ 25.  75.   0.  75.  75.]]]
```

In [28]:
# your code here
print('d=',d)
print('\nf=',f)

d= [[[1.74613522 1.42307971 1.27336438 1.06446082 1.83692143]
  [1.76583375 1.92720415 1.19807632 1.98395152 1.41910702]]

 [[1.11506398 1.27676418 1.91471331 1.62527598 1.89453859]
  [1.90795555 1.16802186 1.76177159 1.60773445 1.40486619]]

 [[1.41023143 1.06989725 1.02931532 1.23889179 1.59646613]
  [1.02337149 1.38677514 1.35447234 1.48550978 1.39831896]]]

f= [[[ 75.  25.  25.  25.  75.]
  [ 75.  75.  25. 100.  25.]]

 [[ 25.  25.  75.  75.  75.]
  [ 75.  25.  75.  75.  25.]]

 [[ 25.  25.  25.  25.  75.]
  [  0.  25.  25.  75.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[['D' 'D' 'D' 'B' 'D']
  ['D' 'D' 'B' 'B' 'B']]

 [['D' 'B' 'D' 'D' 'D']
  ['B' 'B' 'B' 'B' 'E']]

 [['D' 'D' 'D' 'D' 'D']
  ['B' 'D' 'A' 'D' 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [29]:
# your code here
# your code here
h=[]
for i in range(len(d)):
    for x in range(len(d[i])):
        for z in range(len(d[i][x])): 
            h.append(int(f[i][x][z]))
for i in range(len(h)):
    if h[i]==0:
        h[i]='A'
    if h[i]==25:
        h[i]='B'
    if h[i]==50:
        h[i]='C'
    if h[i]==75:
        h[i]='D'
    if h[i]==100:
        h[i]='E'
h=np.array(h)
h=h.reshape(3,2,5)
print(h)

[[['D' 'B' 'B' 'B' 'D']
  ['D' 'D' 'B' 'E' 'B']]

 [['B' 'B' 'D' 'D' 'D']
  ['D' 'B' 'D' 'D' 'B']]

 [['B' 'B' 'B' 'B' 'D']
  ['A' 'B' 'B' 'D' 'B']]]


## Additional Challenges for the Nerds

If you are way ahead of your classmates and willing to accept some tough challenges about Numpy, take one or several of the following Codewar *katas*. 	You need to already possess a good amount of knowledge in Python and statistics because you will need to write Python functions, do loops, write conditionals, and deal with matrices.

* [Insert dashes](https://www.codewars.com/kata/insert-dashes)
* [Thinkful - Logic Drills: Red and bumpy](https://www.codewars.com/kata/thinkful-logic-drills-red-and-bumpy)

Write a function insertDash(num)/InsertDash(int num) that will insert dashes ('-') between each two odd numbers in num. For example: if num is 454793 the output should be 4547-9-3. Don't count zero as an odd number.

Note that the number will always be non-negative (>= 0).

In [120]:
num=454793
lista2=[]
lista3=[]
num=str(num)
for i in num:
    lista3.append(i)
    if int(i)%2!=0:
        x=num.index(i)
        lista2.append(x)
print(lista2)

for a in range(3):
    f=lista2[a]-lista2[a+1]
    if (f==-1):
        print(lista2[a])
print(num)
type(num)
print(lista3)

[1, 3, 4, 5]
3
4
454793
['4', '5', '4', '7', '9', '3']


In [190]:
num=454793
lista2=[]
lista3=[]
lista4=[]
lista5=[]
lista6=[]
num=str(num)
for i in num:
    lista3.append(i)
    x=num.index(i)
    lista2.append(x)
print(lista2)
print(lista3)
for x in range(len(lista2)):
    lista4_element=[lista3[x],lista2[x]]
    lista4.append(lista4_element)
print(lista4)
for z in range(len(lista4)):
    if (int(lista4[z][0])%2!=0):
        lista6.append(lista4[z])
print(lista6)
for h in range(len(lista6)):
    print(lista6[h][1])
    print(lista6[h-1][1])
    if (lista6[h][1]-lista6[h-1][1]==1):
        print(lista6[h])
        

[0, 1, 0, 3, 4, 5]
['4', '5', '4', '7', '9', '3']
[['4', 0], ['5', 1], ['4', 0], ['7', 3], ['9', 4], ['3', 5]]
[['5', 1], ['7', 3], ['9', 4], ['3', 5]]
1
5
3
1
4
3
['9', 4]
5
4
['3', 5]


In [76]:
def soma_digitos(numero):
    soma = 0
    for digito in numero:
        soma = soma + int(digito)

    return soma

def digito_para_array(numero):
    array = []
    for digito in numero:
        array.append(int(digito))
    return array

print(soma_digitos("123456"))
print(digito_para_array("123456"))

21
[1, 2, 3, 4, 5, 6]
